"""init authlog_login_events

Revision ID: 8ff21fec6d98
Revises: 
Create Date: 2025-09-24 11:49:15.302074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff21fec6d98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_authlog_actor_outcome', 'authlog_login_events', ['actor_id', 'outcome'], unique=False)
    op.create_index('ix_authlog_occurred_at', 'authlog_login_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authlog_occurred_at', table_name='authlog_login_events')
    op.drop_index('ix_authlog_actor_outcome', table_name='authlog_login_events')
    # ### end Alembic commands ###
