"""init changes

Revision ID: dfced746400d
Revises: 
Create Date: 2025-09-24 13:47:08.737659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfced746400d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authlog_login_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('auth_method', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('mfa_used', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('log_level', sa.Text(), nullable=False),
    sa.CheckConstraint("actor_type IN ('user','admin','service')", name='ck_actor_type_enum'),
    sa.CheckConstraint("log_level IN ('INFO','WARN','ERROR')", name='ck_log_level_enum'),
    sa.CheckConstraint("outcome IN ('success','failure')", name='ck_outcome_enum'),
    sa.CheckConstraint('actor_id > 0', name='ck_actor_id_positive'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_authlog_actor_outcome', 'authlog_login_events', ['actor_id', 'outcome'], unique=False)
    op.create_index('ix_authlog_occurred_at', 'authlog_login_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authlog_occurred_at', table_name='authlog_login_events')
    op.drop_index('ix_authlog_actor_outcome', table_name='authlog_login_events')
    op.drop_table('authlog_login_events')
    # ### end Alembic commands ###
